training_data_paths:
- "/path/to/tsmixup-data.arrow"
- "/path/to/kernelsynth-data.arrow"
probability:
- 0.9
- 0.1
context_length: 512
prediction_length: 64
input_patch_size: 16
input_patch_stride: 8
min_past: 64
max_steps: 200000
save_steps: 50000
log_steps: 500
per_device_train_batch_size: 32
learning_rate: 0.001
optim: adamw_torch_fused
shuffle_buffer_length: 100
gradient_accumulation_steps: 2
model_id: "facebook/bart-base"
random_init: false
output_dir: "./chronos_bolt_bart_output/"
tf32: true
torch_compile: true
quantiles: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
use_reg_token: true