# Backtest configs for the 27 "zero-shot" datasets.
# These datasets were not seen by Chronos models during training.
- name: monash_traffic
  hf_repo: autogluon/chronos_datasets
  offset: -24
  prediction_length: 24
  num_rolls: 1
- name: monash_covid_deaths
  hf_repo: autogluon/chronos_datasets
  offset: -30
  prediction_length: 30
  num_rolls: 1